const restaurants = {
  businesses: [
    {
      id: "FhZcjPCLrHoZSP-3m7ZdTw",
      alias: "pompier-helsinki",
      name: "Pompier",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/7Ove8-eBe9G7GHtQKX0VOQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/pompier-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 17,
      categories: [
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
        {
          alias: "modern_european",
          title: "Modern European",
        },
      ],
      rating: 5.0,
      coordinates: {
        latitude: 60.1649543127515,
        longitude: 24.9331962618671,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Albertinkatu 29",
        address2: "Albertsgatan 29",
        address3: "",
        city: "Helsinki",
        zip_code: "00180",
        country: "FI",
        state: "18",
        display_address: [
          "Albertinkatu 29",
          "Albertsgatan 29",
          "00180 Helsinki",
          "Finland",
        ],
      },
      phone: "+3589663301",
      display_phone: "+358 9 663301",
      distance: 3154.008184642674,
    },
    {
      id: "wdceec2XGw4PYJ95C-emtQ",
      alias: "bryggeri-helsinki",
      name: "Bryggeri",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/WRWwp7XXJ-kEIOdjt7iKng/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/bryggeri-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 44,
      categories: [
        {
          alias: "breweries",
          title: "Breweries",
        },
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
        {
          alias: "beerbar",
          title: "Beer Bar",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.1680503,
        longitude: 24.9519812,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Sofiankatu 2",
        address2: "",
        address3: "",
        city: "Helsinki",
        zip_code: "00170",
        country: "FI",
        state: "18",
        display_address: ["Sofiankatu 2", "00170 Helsinki", "Finland"],
      },
      phone: "+358102352500",
      display_phone: "+358 10 2352500",
      distance: 2712.720921360248,
    },
    {
      id: "61ZxRWouyOR9vO5zKTpqrQ",
      alias: "konstan-möljä-helsinki",
      name: "Konstan Möljä",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/uJ4HYa4s1KjPg9GZP0dtWw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/konstan-m%C3%B6lj%C3%A4-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 30,
      categories: [
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
        {
          alias: "comfortfood",
          title: "Comfort Food",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 60.1638184,
        longitude: 24.9264202,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Hietalahdenkatu 14",
        address2: null,
        address3: null,
        city: "Helsinki",
        zip_code: "00180",
        country: "FI",
        state: "18",
        display_address: ["Hietalahdenkatu 14", "00180 Helsinki", "Finland"],
      },
      phone: "+35896947504",
      display_phone: "+358 9 6947504",
      distance: 3364.8422433358837,
    },
    {
      id: "kz89xz6bbdxlF64NCEZjnw",
      alias: "juuri-helsinki",
      name: "Juuri",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/w-XpjQjKbwuUjABiJpJBoQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/juuri-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 54,
      categories: [
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
        {
          alias: "tapasmallplates",
          title: "Tapas/Small Plates",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.1639155047475,
        longitude: 24.9462911852249,
      },
      transactions: [],
      price: "€€€€",
      location: {
        address1: "Korkeavuorenkatu 27",
        address2: "Högbergsgatan 27",
        address3: null,
        city: "Helsinki",
        zip_code: "00130",
        country: "FI",
        state: "18",
        display_address: [
          "Korkeavuorenkatu 27",
          "Högbergsgatan 27",
          "00130 Helsinki",
          "Finland",
        ],
      },
      phone: "+3589635732",
      display_phone: "+358 9 635732",
      distance: 3164.282699002643,
    },
    {
      id: "yzQZubsSoyx97hRl4ImTDA",
      alias: "salve-helsinki",
      name: "Salve",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/8huQVaBP0wdrzHdJOvNmuQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/salve-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 50,
      categories: [
        {
          alias: "bistros",
          title: "Bistros",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.161162496413,
        longitude: 24.9300458944161,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Hietalahdenranta 5",
        address2: "Sandvikskajen 5",
        address3: null,
        city: "Helsinki",
        zip_code: "00180",
        country: "FI",
        state: "18",
        display_address: [
          "Hietalahdenranta 5",
          "Sandvikskajen 5",
          "00180 Helsinki",
          "Finland",
        ],
      },
      phone: "+358107664280",
      display_phone: "+358 10 7664280",
      distance: 3606.7963136407893,
    },
    {
      id: "RBQHqgr0jEb7a3k8VIJ3yg",
      alias: "hoku-helsinki",
      name: "Hoku",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/qKtkRNloJHSRqgnwefHPiQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/hoku-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 45,
      categories: [
        {
          alias: "hawaiian",
          title: "Hawaiian",
        },
        {
          alias: "japanese",
          title: "Japanese",
        },
        {
          alias: "korean",
          title: "Korean",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 60.1693803135216,
        longitude: 24.9339735867197,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Urho Kekkosen katu 1",
        address2: "Urho Kekkonens gata 1",
        address3: "",
        city: "Helsinki",
        zip_code: "00100",
        country: "FI",
        state: "18",
        display_address: [
          "Urho Kekkosen katu 1",
          "Urho Kekkonens gata 1",
          "00100 Helsinki",
          "Finland",
        ],
      },
      phone: "+358401646160",
      display_phone: "+358 40 1646160",
      distance: 2668.7470812834868,
    },
    {
      id: "aUUT4i8bzSLj_aOYMYrb2Q",
      alias: "passio-keittiö-ja-baari-helsinki-3",
      name: "PASSIO Keittiö ja Baari",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/A8tcJEeV9dJuIFoWxCrTjw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/passio-keitti%C3%B6-ja-baari-helsinki-3?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 29,
      categories: [
        {
          alias: "modern_european",
          title: "Modern European",
        },
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
      ],
      rating: 5.0,
      coordinates: {
        latitude: 60.1670838,
        longitude: 24.9369496,
      },
      transactions: [],
      price: "€€€€",
      location: {
        address1: "Kalevankatu 13",
        address2: "Kalevagatan 13",
        address3: "",
        city: "Helsinki",
        zip_code: "00100",
        country: "FI",
        state: "18",
        display_address: [
          "Kalevankatu 13",
          "Kalevagatan 13",
          "00100 Helsinki",
          "Finland",
        ],
      },
      phone: "+358207352040",
      display_phone: "+358 20 7352040",
      distance: 2875.125844244159,
    },
    {
      id: "4r_VY8xXtGwPDA80t5C9lg",
      alias: "kolme-kruunua-helsinki-2",
      name: "Kolme Kruunua",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/9KBLzP1Cz-IvgLqvjqZSIA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/kolme-kruunua-helsinki-2?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 30,
      categories: [
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.174376987984,
        longitude: 24.958932832065,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Liisankatu 5",
        address2: null,
        address3: null,
        city: "Helsinki",
        zip_code: "00170",
        country: "FI",
        state: "18",
        display_address: ["Liisankatu 5", "00170 Helsinki", "Finland"],
      },
      phone: "+35891354172",
      display_phone: "+358 9 1354172",
      distance: 2090.888546909091,
    },
    {
      id: "xZisaJBldXe00yqvGq9UEw",
      alias: "sea-horse-helsinki",
      name: "Sea Horse",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/yB_FXb4wIZ1FhnIDG9Vhkw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/sea-horse-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 49,
      categories: [
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.1587659907993,
        longitude: 24.9465446755218,
      },
      transactions: [],
      price: "€€€",
      location: {
        address1: "Kapteeninkatu 11",
        address2: "Kaptensgatan 11",
        address3: null,
        city: "Helsinki",
        zip_code: "00140",
        country: "FI",
        state: "18",
        display_address: [
          "Kapteeninkatu 11",
          "Kaptensgatan 11",
          "00140 Helsinki",
          "Finland",
        ],
      },
      phone: "+3589628169",
      display_phone: "+358 9 628169",
      distance: 3736.3867845216805,
    },
    {
      id: "oukshenaNkkqPhzdjHaI3A",
      alias: "ilves-helsinki",
      name: "Ilves",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/eAvFlekPCGA1y3eoPSdazw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/ilves-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 26,
      categories: [
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.168467858672,
        longitude: 24.9326658364929,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Urho Kekkosen katu 4-6",
        address2: "",
        address3: "",
        city: "Helsinki",
        zip_code: "00100",
        country: "FI",
        state: "18",
        display_address: [
          "Urho Kekkosen katu 4-6",
          "00100 Helsinki",
          "Finland",
        ],
      },
      phone: "+358977467425",
      display_phone: "+358 9 77467425",
      distance: 2787.038868193511,
    },
    {
      id: "Vpq-1ExC2ev_udHFTnkfgA",
      alias: "löyly-helsinki",
      name: "Löyly",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/2LBTM0nteWyI0Kbkp6eq2A/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/l%C3%B6yly-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 39,
      categories: [
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
        {
          alias: "localflavor",
          title: "Local Flavor",
        },
        {
          alias: "saunas",
          title: "Saunas",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.1518407742113,
        longitude: 24.9304517713644,
      },
      transactions: [],
      price: "€€€",
      location: {
        address1: "Hernesaarenranta 4",
        address2: "Ärtholmsstranden 4",
        address3: "",
        city: "Helsinki",
        zip_code: "00150",
        country: "FI",
        state: "18",
        display_address: [
          "Hernesaarenranta 4",
          "Ärtholmsstranden 4",
          "00150 Helsinki",
          "Finland",
        ],
      },
      phone: "+358961286550",
      display_phone: "+358 9 61286550",
      distance: 4607.776489268235,
    },
    {
      id: "P5fKuEGN17XgvRGfGNHKVQ",
      alias: "cafe-bar-9-helsinki",
      name: "Cafe Bar 9",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/V7U16qhZibV69bP2gJv5OQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/cafe-bar-9-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 63,
      categories: [
        {
          alias: "modern_european",
          title: "Modern European",
        },
        {
          alias: "bars",
          title: "Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.1649895,
        longitude: 24.9414501,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Uudenmaankatu 9",
        address2: null,
        address3: null,
        city: "Helsinki",
        zip_code: "00120",
        country: "FI",
        state: "18",
        display_address: ["Uudenmaankatu 9", "00120 Helsinki", "Finland"],
      },
      phone: "+35896214059",
      display_phone: "+358 9 6214059",
      distance: 3059.8895559572816,
    },
    {
      id: "CkUVRpLhgvo4dGZiG939lA",
      alias: "lappi-helsinki",
      name: "Lappi",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/3-FzzPLVXFRZlIyGAHLfVg/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/lappi-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 34,
      categories: [
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.1665611,
        longitude: 24.9367809,
      },
      transactions: [],
      price: "€€€€",
      location: {
        address1: "Annankatu 22",
        address2: null,
        address3: null,
        city: "Helsinki",
        zip_code: "00100",
        country: "FI",
        state: "18",
        display_address: ["Annankatu 22", "00100 Helsinki", "Finland"],
      },
      phone: "+3589645550",
      display_phone: "+358 9 645550",
      distance: 2920.543377712825,
    },
    {
      id: "q5f2NC01K6hc4SLQG5olmA",
      alias: "pompier-helsinki-2",
      name: "Pompier",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/mCcfJG6p08dg47qFECvyZw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/pompier-helsinki-2?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 13,
      categories: [
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
        {
          alias: "modern_european",
          title: "Modern European",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 60.1671925257657,
        longitude: 24.9492107925732,
      },
      transactions: [],
      price: "€€€",
      location: {
        address1: "Eteläesplanadi 8",
        address2: "Södra Esplanaden 8",
        address3: "",
        city: "Helsinki",
        zip_code: "00130",
        country: "FI",
        state: "18",
        display_address: [
          "Eteläesplanadi 8",
          "Södra Esplanaden 8",
          "00130 Helsinki",
          "Finland",
        ],
      },
      phone: "+3589663300",
      display_phone: "+358 9 663300",
      distance: 2799.6087162632157,
    },
    {
      id: "N98WgUkrOxtD3x-oRZWSMw",
      alias: "gaijin-helsinki",
      name: "Gaijin",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/K0g2_5D1-T6NNAQMJO-3Mw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/gaijin-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 53,
      categories: [
        {
          alias: "asianfusion",
          title: "Asian Fusion",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.1658938460497,
        longitude: 24.9420316944995,
      },
      transactions: [],
      price: "€€€",
      location: {
        address1: "Bulevardi 6",
        address2: "",
        address3: "",
        city: "Helsinki",
        zip_code: "00120",
        country: "FI",
        state: "18",
        display_address: ["Bulevardi 6", "00120 Helsinki", "Finland"],
      },
      phone: "+358103229386",
      display_phone: "+358 10 3229386",
      distance: 2960.8459719588973,
    },
    {
      id: "-ZkyS1K2v3ac9lpnMOfaJQ",
      alias: "korea-house-helsinki",
      name: "Korea House",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/7kMuOLt97FWfLsMgY61aRA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/korea-house-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 18,
      categories: [
        {
          alias: "korean",
          title: "Korean",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.1728592,
        longitude: 24.9570103,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Mariankatu 19",
        address2: null,
        address3: null,
        city: "Helsinki",
        zip_code: "00170",
        country: "FI",
        state: "18",
        display_address: ["Mariankatu 19", "00170 Helsinki", "Finland"],
      },
      phone: "+35891357158",
      display_phone: "+358 9 1357158",
      distance: 2220.5861561783063,
    },
    {
      id: "UJ-68SUiQf-WboqFp0ypXA",
      alias: "kolmon3n-helsinki",
      name: "Kolmon3n",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/RlUttK70uHCkcpRzrhoKSQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/kolmon3n-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 11,
      categories: [
        {
          alias: "burgers",
          title: "Burgers",
        },
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 60.1821012,
        longitude: 24.9501554,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Kolmas linja 11",
        address2: "Tredje linjen 11",
        address3: "",
        city: "Helsinki",
        zip_code: "00530",
        country: "FI",
        state: "18",
        display_address: [
          "Kolmas linja 11",
          "Tredje linjen 11",
          "00530 Helsinki",
          "Finland",
        ],
      },
      phone: "+358447753333",
      display_phone: "+358 44 7753333",
      distance: 1147.7362882207153,
    },
    {
      id: "Rehov3sxbHwXpVoRCRrRqw",
      alias: "mei-lin-helsinki",
      name: "Mei Lin",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/EGg7edI92SZp-W9lY9fGGQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/mei-lin-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 11,
      categories: [
        {
          alias: "chinese",
          title: "Chinese",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 60.16682,
        longitude: 24.92958,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Lapinlahdenkatu 9",
        address2: "Lappviksgatan 9",
        address3: "",
        city: "Helsinki",
        zip_code: "00180",
        country: "FI",
        state: "18",
        display_address: [
          "Lapinlahdenkatu 9",
          "Lappviksgatan 9",
          "00180 Helsinki",
          "Finland",
        ],
      },
      phone: "+358451032688",
      display_phone: "+358 45 1032688",
      distance: 3024.34888815063,
    },
    {
      id: "qoyqtjDTTJsoRDduVoSfLw",
      alias: "savotta-helsinki",
      name: "Savotta",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/VfTPFdbo6WBV_rSM03KLXw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/savotta-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 37,
      categories: [
        {
          alias: "scandinavian",
          title: "Scandinavian",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.1689736101652,
        longitude: 24.9530501909639,
      },
      transactions: [],
      price: "€€€€",
      location: {
        address1: "Aleksanterinkatu 22",
        address2: "Alexandersgatan 22",
        address3: null,
        city: "Helsinki",
        zip_code: "00170",
        country: "FI",
        state: "18",
        display_address: [
          "Aleksanterinkatu 22",
          "Alexandersgatan 22",
          "00170 Helsinki",
          "Finland",
        ],
      },
      phone: "+358974255588",
      display_phone: "+358 9 74255588",
      distance: 2616.2082804041897,
    },
    {
      id: "hS6ycWfHNxqBuLk9yYt1_A",
      alias: "töölön-sävel-helsinki",
      name: "Töölön Sävel",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/PN_lZFxwuQ_69clZqPKVig/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/t%C3%B6%C3%B6l%C3%B6n-s%C3%A4vel-helsinki?adjust_creative=p2OuogDnIgjosrpThJVAAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=p2OuogDnIgjosrpThJVAAg",
      review_count: 12,
      categories: [
        {
          alias: "gastropubs",
          title: "Gastropubs",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 60.1781726318713,
        longitude: 24.9224498823596,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "Runeberginkatu 40",
        address2: "Runebergsgatan 40",
        address3: "",
        city: "Helsinki",
        zip_code: "00260",
        country: "FI",
        state: "18",
        display_address: [
          "Runeberginkatu 40",
          "Runebergsgatan 40",
          "00260 Helsinki",
          "Finland",
        ],
      },
      phone: "+358447555959",
      display_phone: "+358 44 7555959",
      distance: 2113.666914966135,
    },
  ],
  total: 1400,
  region: {
    center: {
      longitude: 24.947891235351562,
      latitude: 60.19236148732381,
    },
  },
};
export default restaurants;
